### PR TITLE
Improved network and power model required for LEAF

### PR DESCRIPTION
**Pull request by birnbaum**
1. Improved network model
The existing network topology was highly coupled to BRITE topology files, had an unhandy interface and a O(n^3) worst-case complexity for finding shortest paths, implementing only the Floyd–Warshall algorithm. It was replaced with a network topology based on JGraphT. Users can now make use of the many features and algorithms implemented in this library.

2. Improved power model
The existing power models were only working with data center hosts and were impacting the performance of hosts. They were replaced with a general power model that can be used for hosts and network links but is entirely decoupled from their implementation.

### CODE REVIEW

**Comment by birnbaum** [comment]
Sorry, this PR was not meant to be issued against this repository, my bad!

**Comment by manoelcampos** [comment]
Hello @birnbaum 
I've taken a look at your PR and checked that your LEAF simulator is based on CloudSim Plus.
First of all, thanks for using CloudSim Plus, but directly changing the simulator code is a mistake that lots of CloudSim users have been making. 
This led to lots of CloudSim forks that were abandoned along the way.
I see you have some interesting changes and I don't know if you made more on your fork.
But I'm open to discuss the changes I see how we can help each other.
However, this PR would need to be broken in several ones, each one focused in solving a specific issue.

If you are interested, we can arrange some time to talk.

**Comment by birnbaum** [comment]
Hey @manoelcampos! First of all thanks to you for your hard work on improving CloudSim, this project is really great to work with!

I had to adapt a few things in the CloudSim Plus core as the interfaces of the current power and network models were not flexible enough for my use case (https://github.com/birnbaum/LEAF). I squashed all my changes into a single commit so the supervisor of my Master's thesis can see what changes I've made on my fork - it was not yet meant to be issued against this repo :)

However, I do think that some of the changes I've made could be contributed back to CloudSim Plus. I'm pretty busy the next 1-2 weeks but I'll definitely get back to you with proper PRs and some ideas on how to further improve CloudSim Plus.

**Comment by manoelcampos** [comment]
I think we should discuss before you take the effort. If you are interested and have time, just let me know.

**Comment by birnbaum** [comment]
Hey @manoelcampos! Sorry for the late reply, I was very busy the last few months but now I'm interested in having a chat with you sometime to maybe contribute some of my work to CloudSim Plus. In particular, I have questions/ideas about the following:
1. Improved power model (more resilient in some edge cases and more decoupled from the core implementation)
2. Improved network model (based on a modern graph/networking lib)
3. Improved performance (noticed some memory leaks in the main event loop that slow down the simulations dramatically when there are a lot of events)

Also, I plan to write an adapter for https://mosaik.offis.de

**Comment by manoelcampos** [comment]
Hey @birnbaum 
No problem. Thanks for getting back to me.
Could you add me in Hangout? My email address is manoelcampos at gmail.

**Comment by birnbaum** [comment]
Hi @manoelcampos, have you received the invitation? I'm pretty busy this week but from next week on I'm available :)

**Comment by manoelcampos** [comment]
No, I haven't. Could you please send an email to the same address?

**Pull request closed without merging**
