### PR TITLE
Close #291

### LINKED ISSUE #291: Simplifies Mips Share for CloudletSchedulers and VmSchedulers to reduce redundancy and computational complexity
The `List<Double> mipsShare` used in `CloudletScheduler` and `VmScheduler` is iterated over and over again as simulation processing is updated. As more VMs and Cloudlets, the complexity increases.

All PEs are expected to have the same MIPS capacity. That is even documented in VmSimple constructor and PeSimple class. This way, it doesn't make sense to have a list for the MIPS capacity of a physical or virtual PE.
That just adds up computational complexity.

I don't think it makes sense to allocate different MIPS capacity across the VM PEs.
Therefore, the list is replaced by a class that stores the MIPS requested or allocated capacity for used VM PEs.

### PR DESCRIPTION
**Pull request by manoelcampos**
# Close #291

Performance improvements for large-scale experiments are huge with this new version.

performance-improvement

### CODE REVIEW

**Comment by manoelcampos** [comment]
Hey @CharafeddineMechalikh
Could you please try this 6.2.0 version with the experiments we discussed?
Thanks.

**Comment by CharafeddineMechalikh** [comment]
Hello,
I'm trying it.
I noticed a little drop in performance.
Now I'm doing multple experiments, and I will plot the average duration and
send it to you this afternoon.
Thank you

**Comment by manoelcampos** [comment]
@CharafeddineMechalikh I've just merged the changes.
The 6.2.0 release will be available in Maven Central in some minutes.
Thanks for your collaboration.

**Comment by CharafeddineMechalikh** [comment]
Well received, thank your for this amazing work. I will update to the
latest version as soon as possible.

**Pull request merged**
