### PR TITLE
Purge finished entities from list

### PR DESCRIPTION
**Pull request by birnbaum**
This is a hacky fix that shouldn't be merged to master without revision.

I don't have the time right now to implement a more meaningful approach, but the ever-increasing entities list has been a performance problem for many of my experiments.

### CODE REVIEW

**Review by manoelcampos — COMMENTED** [review]
Hey @birnbaum 
This is very welcome improvement.
I've made some refactoring and added a temporary purgeEntities attribute
that will enable performing some tests to ensure simulation results are correct.

There is a new simulation scenario file to be transformed in an integration test latter on.
I take a look at it again tomorrow.

I'm wondering if you created the removeEntityList to ensure entires are removed just on the next simulation tick. If it's not that, we can use the entities.removeIf instead of this additional list, that just increases time complexity.

**Comment by birnbaum** [comment]
Hi @manoelcampos,

thanks for your work! Yes, removeIf makes sense here! My solution was just one that "works" for my use case, it's in no way clean. Maybe there is also a way to detect unused entities (a bit like a gc), I just introduced this time-based purging because otherwise I sometimes deleted finished entities that were still referenced by running entities

**Comment by manoelcampos** [comment]
Hey @birnbaum 

I've created the FinishedEntitiesPurgeTest test class to check multiple results of an entire simulation scenario.
My concern was that by removing finished entities, some events were lost, causing inconsistency in results.
The test class provides lots of tests to check that.

I executed all tests and everything is working fine. I also removed the purgeEntities() method and changed the implementation to reduce time complexity. Now, the purge process is inside the `CloudSimEntity.shutdown()` method, not requiring iteration.

I also improved the DatacenterBroker to enable it to shutdown after becoming idle. Check the new shutdownWhenIdle attribute. By default, despite the broker was able to destroy idle VMs, the broker was just being destroyed when the simulation finished. Now, by default, it will be shutdown after becoming idle.

If you could try with your experiments to check how it works, it will be great.
I don't have any other thoughts on that and I'm ready to merge.
Please let me know what you think and if you are planning other changes before we release the 6.0.0 version.

Thank you so much for the collaboration.

**Comment by birnbaum** [comment]
Hey Manoel,

I integrated all new Changes into LEAF and it works like a charm :) Thanks a lot for your help!

I have some stashed changes for implementing a `PowerModelVm` in order to get rid of the `powerConsumption(time)` in `UtilizationHistory`/`VmUtilizationHistory` (power consumption doesn't really belong in this class I think), but I'll not be able to follow up on that soon.

So for now, I have no more contributions planned, we can go for CloudSim Plus v6 🍾
Once it's released I'll update LEAF, so that it doesn't run on the forked/patched version any more

**Comment by manoelcampos** [comment]
Awesome. I have some concerns about the entities list. It is instantiated as an ArrayList. That has great performance when iterating, but for large scale experiments that receives lots of entities dynamically, that may have a huge penalty on internal copy operations to expand the list.

The removal of entities also has a linear time complexity. But it's require some benchmarks. I'll take a look a it further, since it's just an internal change. 

About the VM power model, it will be welcome too. But let's release this 6.0 version.

Thanks for everything. And if you need something that I can help, just get in touch.

**Review by manoelcampos — APPROVED** [review]

**Pull request merged**
